@extends('front.layouts.master')
@section('title',$title)
 @section('content')
 <section class="inner-banner" style="background-image:url({{ asset('public/web/images/page-title-bg.png') }});">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-inner" data-aos="fade-up" data-aos-once="true">
                        <h1 class="page-title">FAQ'S</h1>
                        <ul class="page-list">
                            <li><a href="{{ URL::to('/') }}">Home</a></li>
                              <li>FAQ'S</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

     <section class="faq-section py-5">
        <div class="container">
            <div class="accordion" id="accordionExample">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            Introduction
                    </button>
                    </h2>
                    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            <p>www.testpaperlive.com is an online exam portal, owned by Testpaperlive, a company incorporated in Jaipur, Rajasthan, India, for imparting education and concept in relation to preparation and test series modules for entrance
                                exams of all state and central government competitive exams in India through digital modules.</p>
                            <p>Our passionate individuals working dedicatedly to bring quality video lectures, model paper &amp; test series. Developing concepts in Aptitude, Reasoning, English, General knowledge, Computer, Professional Knowledge.</p>
                            <p>Providing advance Mock Test series through a community of professionals with the purpose of clearing concepts of Aptitude, Reasoning, English, General knowledge, Computer, Professional Knowledge.
                            </p>

                            <p><strong>Feel free to get in touch with our support team</strong></p>
                            <p>If you have any questions about this testpaperlive or your experience with the Service, you can e-mail us at support@testpaperliver.com</p>
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingTwo">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                            General
                    </button>
                    </h2>
                    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            <p>"www.testpaperlive.com" owned and operated by Testpaperlive, You are advised to read and understand these Terms carefully as moving past the home page, or using any of the services shall be taken to mean that you have read
                                and agreed to all of the policies, which constitute a legally binding agreement between you and the website. These terms are to be read along with the Privacy Policy and any other policies on the website. This document
                                is an electronic record published in accordance with the provisions of the Information Technology (Intermediaries guidelines) Rules, 2018 that require publishing the Rules and Regulations, Privacy Policy and Terms of Service
                                for access or usage of the website and being generated by a computer system, it does not require any physical or digital signatures. For the purpose of these Terms of Use, along with any amendments to the same, and wherever
                                the context so requires "You", "Your" or "User" refer to the person visiting, accessing, browsing through and/or using the Website at any point in time. The term "We", "Us", "Our" shall mean and refer to the website and/or
                                the Company, depending on the context. The headings of each section in this Agreement are only for the purpose of organising the various provisions under this Agreement in an orderly manner. These headings shall not be
                                used by either party to interpret the provisions contained under them in any manner. Further, the headings have no legal or contractual value. We hold the sole right to modify the Terms of Service without prior permission
                                from you or providing notice to you. The relationship creates on You a duty to periodically check the Terms of Service and stay updated on its requirements. If You continue to use the Website or avail any of its services
                                without registration following such change, this is deemed as consent by You to the so amended policies. Your continued use of the Website is conditioned upon your compliance with the Terms of Service, including but not
                                limited to compliance with the Terms of Service even after alterations, if any.</p>
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingThree">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                            Registration
                    </button>
                    </h2>
                    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            <p>In connection with registering for and using the Service, you agree </p>
                            <p>1. to provide accurate, current and complete information about you and/or your as requested by Testpaperlive; </p>
                            <p>2. to maintain the confidentiality of your password and other information related to the security of your account; </p>
                            <p>3. to maintain and promptly update any registration information you provide to Testpaperlive while registering or during your usage of Testpaperlive's services, to keep such information accurate, current and complete; </p>
                            <p>4. to be fully responsible for all use of your account and for any actions that take place through your account; </p>
                            <p>5. You consent to be contacted by us via phone calls and/or SMS notifications, in case of any order or shipment or delivery related updates; and </p>
                            <p>6. You are required to provide your examination registration information for the purpose of our internal estimation of successful candidates. If you do not provide the information, your partial or full access to the website
                                content and/or other Testpaperlive services may be blocked. </p>
                            <p> <strong>No refund will be provided in such scenario. We assure you that we will not use this information for any other purpose or share this information with any third party</strong></p>
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingFour">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                            Copy right and trademark
                    </button>
                    </h2>
                    <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            <p>
                                The Company, its suppliers and licensors expressly reserve all Testpaperlive property rights in all text, programs, products, processes, technology, images, content and other materials which appear on the Site. Access to or use of the Site does not confer
                                and should not be considered as conferring upon anyone any license to the Company or any third party's Testpaperlive property rights. All rights, including copyright, in and to the Site are owned by or licensed to the Company.
                                Any use of the Site or its contents, including copying or storing it or them in whole or part is prohibited without the permission of the Company. </p>
                            <p>You may not modify, distribute or re-post anything on the Site for any purpose. The names and logos and all related product and service names, design marks and slogans are the trademarks/service marks of the Company, its affiliates,
                                its partners or its suppliers/service providers. All other marks are the property of their respective owners. No trademark or service mark license is granted in connection with the materials contained on the Site. Access
                                to or use of the Site does not authorize anyone to use any name, logo or mark in any manner. References on the Site to any names, marks, products or services of third parties or hypertext links to third party sites or information
                                are provided solely as a convenience to you and do not in any way constitute or imply the Company's endorsement, sponsorship or recommendation of the third party, the information, its product or services. The Company is
                                not responsible for the content of any third party sites and does not make any representations regarding the content or accuracy of material on such sites. If you decide to access a link of any third party websites, you
                                do so entirely at your own risk and expense.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

  
 @endsection
 
 @section('script')
 <script>
function search(){ //alert(href);
   
        $.ajax({

            type: 'GET',

             url: '{{ URL::to('/dashboard') }}',

            data: $('#filter_document').serialize(),

            beforeSend: function(){

              $.LoadingOverlay("show");

            },

            success: function(data){ 
				  $('#replace-div').html('');
                $('#replace-div').html(data);
                $.LoadingOverlay("hide");

                return false;

            }

        });
    }
$('.view_type').click(function(){
		var id = $(this).attr("data-id");
	
		$("#view_type").val(id);
		if(id == 1){
			$(".btn-col").removeClass("active");
		}else{
			$(".btn-grid").removeClass("active")
		}
		$(this).addClass("active");
		search();
	});

 </script>
 @endsection